[package]
name = "rudg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ra_ap_syntax = "0.0.104"
clap = { version = "3.1.18", features = ["derive", "cargo"] }
dot_graph = "0.1.0"