name: cargo publish

on:
  push:
    tags:
    - "v*"

jobs:
  cargo_publish:
    name: Publish to Crates.io
    runs-on: ubuntu-latest
    environment: cargo
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo publish